language: haskell
before_install:
env:
 - GHCVER=7.4
 - GHCVER=7.6
 - GHCVER=7.8
 - GHCVER=7.10
 - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$HOME/.cabal/bin:$PATH
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - ghc --version
 - ghc-pkg list | grep Cabal
 - cabal configure --enable-tests
#--enable-library-coverage || cabal configure --enable-tests --enable-coverage
 - cabal build
 - cabal test

#after_script:
# - cabal install hpc-coveralls
# - hpc-coveralls --exclude-dir=test test
